### ISSUE TITLE
add support for cdn

### ISSUE THREAD

**Issue by 0xJoichiro** [subquery/subquery-component-library#105]
cnd would help out in this issue https://github.com/subquery/subql/issues/1515

Examples are as follows =>

- https://mui.com/material-ui/getting-started/installation/#cdn
- https://ant.design/docs/react/introduce#import-in-browser

**Comment by HuberTRoy** [comment]
https://cdn.jsdelivr.net/npm/@subql/components@1.0.3-28/dist/subquery-components.es.js
https://cdn.jsdelivr.net/npm/@subql/components@1.0.3-28/dist/subquery-components.css
