### ISSUE TITLE
Add commonjs module to CDN

### ISSUE THREAD

**Issue by stwiname** [subquery/subquery-component-library#108]
Following on from https://github.com/subquery/subquery-component-library/issues/105

Subql SDK want to use the graphql playground in the query service and needs a commonjs module 

Ideally its automated so new releases include the output

**Comment by HuberTRoy** [comment]
New version 2.0.0 support both cjs and esm.

import cjs via `import {xxx} from '@subql/components/dist/subquery-components.cjs'`, for GraphiQL component need to via `import {xxx} from '@subql/components/dist/common/GraphiQL/index.cjs'`.

CDN prefix: `https://cdn.jsdelivr.net/npm/@subql/components@2.0.0/dist/`

CSS file is the same.
